config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'person/:restname'=>'person#show', :as => :restaurant

  get 'restaurant/info/:restname' => 'person#info', :as=> :info

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/person_controller.rb
class PersonController < ApplicationController

  def show
    @restaurants= params[:restname]

    if params[:restname].downcase == "sammysues"
      @text = "Best wings around!!!"
      @pic = "the_rail.jpg"
    elsif params[:restname].downcase == "krockers"
      @text = "Best tots around!!!"
      @pic = "the_rail.jpg"
    elsif params[:restname].downcase == "therail"
      @text = "Best burgers & pretzel bites with beer cheese around!!!"
      @pic= "the_rail.jpg"
    else
      @text = "Best pizza around!!!"
      @pic = "Park-Street.jpg"
    end
  end

  def info

  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @restaurants=[
      "SammySues",
      "Krockers",
      "TheRail",
      "ParkStreet"
    ]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/person_helper.rb
module PersonHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BootstrappingRails</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" integrity="sha384-aUGj/X2zp5rLCbBxumKTCw2Z50WgIr1vs/PFN4praOTvYXWlVyh2UtNUU0KAUhAX" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/person/info.html.erb
<h1><% @restname %></h1>

<%= link_to params[:restname], restaurant_path(:restname => params[:restname])%>
<p><%= @text %></p>

app/views/person/show.html.erb
<h1>T-County Restaurant name: <%= params[:restname] %></h1>
<div class= "container">
<div class="row">
  <div class= "col-xs-9 col-md-12">
    <p><%= @text%></p>
    <div class="col-xs-12 col-md-3 col-lg-4 pull-right">
      <%= image_tag @pic%>
    </div>
  </div>
    <div class="row">
      <div class= "col-xs-12">
        <p><%= link_to "Back", root_path %></p>
      </div>
    </div>
</div>

app/views/welcome/index.html.erb
<h1> Welcome to T-County Eats.</h1>

<ul>
  <% @restaurants.each do |restname| %>
    <li><%= link_to restname, restaurant_path(:restname=> restname) %> </li>
  <% end %>
</ul>

<%=image_tag "Park-Street.jpg" %>